# Generated by Django 5.2.8 on 2025-12-04 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentexamattempt',
            name='verification_code',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
    ]
