# Generated by Django 5.2.8 on 2025-12-04 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0003_certificate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentexamattempt',
            name='verification_code',
        ),
        migrations.AddField(
            model_name='certificate',
            name='verification_code',
            field=models.CharField(default='TEMP', max_length=20, unique=True),
            preserve_default=False,
        ),
    ]
