# Generated by Django 5.2.8 on 2025-12-08 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_enrollment_lessonprogress'),
    ]

    operations = [
        migrations.AddField(
            model_name='lessonprogress',
            name='progress_percent',
            field=models.IntegerField(default=0),
        ),
    ]
