# Generated by Django 4.2.7 on 2026-01-08 12:22

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("courses", "0002_resource"),
        ("courses", "0007_resource"),
    ]

    operations = []
